# action.yml
name: 'Authelia Validate'
description: 'Validate the Authelia configuration file'
branding:
  icon: check
  color: blue
inputs:
  file-path:
    description: 'Path to configuration file'
    required: true
    default: './configuration.yml'
outputs:
  errors:
    description: 'Errors returned if any'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file-path }}
