on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authelia validate success
        id: success
        uses: bubylou/authelia-validate@main
        with:
          file-path: .github/config-success.yml
          version: v4.37.5

      - name: Authelia validate failure
        id: failure
        continue-on-error: true
        uses: bubylou/authelia-validate@main
        with:
          file-path: .github/config-failure.yml
          version: v4.36.9
