on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authelia validate
        id: authelia
        uses: bubylou/authelia-validate@v2
